### ISSUE TITLE
Error when receiving a response in a telegram

### ISSUE THREAD

**Issue by Alekcan** [karfly/chatgpt_telegram_bot#10]
I made a bot through PyCharm and Docker. But in some, instead of an answer, a long error in telegram message. Am I doing something wrong?

An exception was raised while handling an update
.
.
.
NameError: name 'telegram' is not defined

**Comment by karfly** [comment]
What command do you use to run the code?

**Comment by Alekcan** [comment]
> What command do you use to run the code?
docker compose --env-file config/config.env up --build
After which I ran this in Docker.

The bot works, but sometimes it can send a long error instead of a response. If you repeat the question again, it might work fine. Sometimes it didn't happen for 30+ minutes. But it happened that bot answered with an error 2-3 times in a row.

**Comment by karfly** [comment]
What exact error does it show?

**Comment by Alekcan** [comment]
I edited a little to remove personal information. This response may come from a telegram message.

```
An exception was raised while handling an update
update = {
  "update_id": delete
  "message": {
    "chat": {
      "id": id,
      "type": "private",
      "first_name": "delete",
      "username": "delete"
    },
    "text": "question",
    "group_chat_created": false,
    "entities": [],
    "new_chat_members": [],
    "new_chat_photo": [],
    "message_id": 480,
    "delete_chat_photo": false,
    "caption_entities": [],
    "date": 1674346521,
    "supergroup_chat_created": false,
    "photo": [],
    "channel_chat_created": false,
    "from": {
      "is_bot": false,
      "username": "delete",
      "first_name": "delete",
      "id": id,
      "language_code": "en"
    }
  }
}

Traceback (most recent call last):
  File "bot/bot.py", line 133, in message_handle
    await update.message.reply_text(answer, parse_mode=ParseMode.HTML)
  File "/usr/local/lib/python3.8/site-packages/telegram/_message.py", line 784, in reply_text
    return await self.get_bot().send_message(
  File "/usr/local/lib/python3.8/site-packages/telegram/_bot.py", line 238, in decorator
    result = await func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/telegram/_bot.py", line 637, in send_message
    return await self._send_message(  # type: ignore[return-value]
  File "/usr/local/lib/python3.8/site-packages/telegram/ext/_extbot.py", line 253, in _send_message
    result = await super()._send_message(
  File "/usr/local/lib/python3.8/site-packages/telegram/_bot.py", line 346, in _send_message
    result = await self._post(
  File "/usr/local/lib/python3.8/site-packages/telegram/_bot.py", line 310, in _post
    return await request.post(
  File "/usr/local/lib/python3.8/site-packages/telegram/request/_baserequest.py", line 160, in post
    result = await self._request_wrapper(
  File "/usr/local/lib/python3.8/site-packages/telegram/request/_baserequest.py", line 319, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Can't parse entities: tag "span" must have class "tg-spoiler" at byte offset 51

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/telegram/ext/_application.py", line 945, in process_update
    await coroutine
  File "/usr/local/lib/python3.8/site-packages/telegram/ext/_handler.py", line 135, in handle_update
    return await self.callback(update, context)
  File "bot/bot.py", line 134, in message_handle
    except telegram.error.BadRequest:
NameError: name 'telegram' is not defined
```

**Comment by karfly** [comment]
I see the problem and I will fix it as soon as I get to my laptop.

You can now hotfix it by adding `import telegram` in the beginning of the `bot/bot.py` file.

**Comment by karfly** [comment]
Fixed the problem with 81066cf0c522ea68c0381c66d97c7079a1ce05af.
Can you check if it works now?

**Comment by Alekcan** [comment]
Through 5 replies I got it again, slightly modified.

```
An exception was raised while handling an update
update = {
  "update_id": delete,
  "message": {
    "chat": {
      "id": id,
      "type": "private",
      "first_name": "delete",
      "username": "delete"
    },
    "text": "question",
    "group_chat_created": false,
    "entities": [],
    "new_chat_members": [],
    "new_chat_photo": [],
    "message_id": 731,
    "delete_chat_photo": false,
    "caption_entities": [],
    "date": 1674416607,
    "supergroup_chat_created": false,
    "photo": [],
    "channel_chat_created": false,
    "from": {
      "is_bot": false,
      "username": "delete",
      "first_name": "delete",
      "id": id,
      "language_code": "en"
    }
  }
}

Traceback (most recent call last):
  File "bot/bot.py", line 134, in message_handle
    await update.message.reply_text(answer, parse_mode=ParseMode.HTML)
  File "/usr/local/lib/python3.8/site-packages/telegram/_message.py", line 784, in reply_text
    return await self.get_bot().send_message(
  File "/usr/local/lib/python3.8/site-packages/telegram/_bot.py", line 238, in decorator
    result = await func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/telegram/_bot.py", line 637, in send_message
    return await self._send_message(  # type: ignore[return-value]
  File "/usr/local/lib/python3.8/site-packages/telegram/ext/_extbot.py", line 253, in _send_message
    result = await super()._send_message(
  File "/usr/local/lib/python3.8/site-packages/telegram/_bot.py", line 346, in _send_message
    result = await self._post(
  File "/usr/local/lib/python3.8/site-packages/telegram/_bot.py", line 310, in _post
    return await request.post(
  File "/usr/local/lib/python3.8/site-packages/telegram/request/_baserequest.py", line 160, in post
    result = await self._request_wrapper(
  File "/usr/local/lib/python3.8/site-packages/telegram/request/_baserequest.py", line 319, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Can't parse entities: can't find end tag corresponding to start tag code

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/telegram/ext/_application.py", line 945, in process_update
    await coroutine
  File "/usr/local/lib/python3.8/site-packages/telegram/ext/_handler.py", line 135, in handle_update
    return await self.callback(update, context)
  File "bot/bot.py", line 137, in message_handle
    await update.message.reply_text(answer)
  File "/usr/local/lib/python3.8/site-packages/telegram/_message.py", line 784, in reply_text
    return await self.get_bot().send_message(
  File "/usr/local/lib/python3.8/site
```

**Comment by karfly** [comment]
Try to update your code: `git pull`.
Several days ago I added [try-except check](https://github.com/karfly/chatgpt_telegram_bot/blob/main/bot/bot.py#L135) for bad symbols in reply messages. But it looks like this check doesn't work in your runs.

**Comment by Alekcan** [comment]
I downloaded the bot yesterday and I have these lines.
This is not critical, if I find a dependency in which cases he more often answers with an error, I'll let you know.
Maybe something is going wrong because of the messages in russian language (I'm from Ukraine).

**Comment by karfly** [comment]
Can you show full traceback for this https://github.com/karfly/chatgpt_telegram_bot/issues/10#issuecomment-1399589004?

**Comment by Alekcan** [comment]
> Can you show full traceback for this [#10 (comment)](https://github.com/karfly/chatgpt_telegram_bot/issues/10#issuecomment-1399589004)?

Sorry I don't know how to do it or where to get it.

**Comment by karfly** [comment]
@Alekcan is your problem finally solved?
