### ISSUE TITLE
Something went wrong during completion.

### ISSUE THREAD

**Issue by xawwnee** [karfly/chatgpt_telegram_bot#100]
Something went wrong during completion. Reason: You exceeded your current quota, please check your plan and billing details.

These keep showing in build log:

```
Mar 8 09:52:27 PM  Traceback (most recent call last):
Mar 8 09:52:27 PM    File "bot/bot.py", line 237, in error_handle
Mar 8 09:52:27 PM      await context.bot.send_message(update.effective_chat.id, message_chunk, parse_mode=ParseMode.HTML)
Mar 8 09:52:27 PM  AttributeError: 'NoneType' object has no attribute 'effective_chat'
```
Also this
```
Mar 8 09:52:27 PM      await callback(update, context)
Mar 8 09:52:27 PM    File "bot/bot.py", line 239, in error_handle
Mar 8 09:52:27 PM      await context.bot.send_message(update.effective_chat.id, "Some error in error handler")
Mar 8 09:52:27 PM  AttributeError: 'NoneType' object has no attribute 'effective_chat'
```
After few minutes the bot stops itself and build status shows failed.

**Comment by karfly** [comment]
It means, that you exceeded your OpenAI API quota

**Comment by xawwnee** [comment]
> It means, that you exceeded your OpenAI API quota

Ok. :)
