### ISSUE TITLE
Cannot install - constantly getting an error

### ISSUE THREAD

**Issue by gaivalue** [karfly/chatgpt_telegram_bot#125]
When I run

```
% docker-compose --env-file config/config.yml up --build
```

I get:

```
WARNING: Python-dotenv could not parse statement starting at line 1
WARNING: Python-dotenv could not parse statement starting at line 2
WARNING: Python-dotenv could not parse statement starting at line 3
WARNING: Python-dotenv could not parse statement starting at line 4
WARNING: Python-dotenv could not parse statement starting at line 5
WARNING: Python-dotenv could not parse statement starting at line 6
WARNING: Python-dotenv could not parse statement starting at line 8
WARNING: Python-dotenv could not parse statement starting at line 9
Traceback (most recent call last):
  File "/Users/tonysimonovskiy/opt/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/tonysimonovskiy/opt/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/tonysimonovskiy/opt/anaconda3/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/tonysimonovskiy/opt/anaconda3/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/tonysimonovskiy/opt/anaconda3/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/tonysimonovskiy/opt/anaconda3/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/Users/tonysimonovskiy/opt/anaconda3/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/Users/tonysimonovskiy/opt/anaconda3/lib/python3.8/site-packages/docker/transport/unixconn.py", line 30, in connect
    sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tonysimonovskiy/opt/anaconda3/lib/python3.8/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/Users/tonysimonovskiy/opt/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/Users/tonysimonovskiy/opt/anaconda3/lib/python3.8/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/tonysimonovskiy/opt/anaconda3/lib/python3.8/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/Users/tonysimonovskiy/opt/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/tonysimonovskiy/opt/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/tonysimonovskiy/opt/anaconda3/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/tonysimonovskiy/opt/anaconda3/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/tonysimonovskiy/opt/anaconda3/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/tonysimonovskiy/opt/anaconda3/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/Users/tonysimonovskiy/opt/anaconda3/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/Users/tonysimonovskiy/opt/anaconda3/lib/python3.8/site-packages/docker/transport/unixconn.py", line 30, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tonysimonovskiy/opt/anaconda3/lib/python3.8/site-packages/docker/api/client.py", line 214, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
  File "/Users/tonysimonovskiy/opt/anaconda3/lib/python3.8/site-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
  File "/Users/tonysimonovskiy/opt/anaconda3/lib/python3.8/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/Users/tonysimonovskiy/opt/anaconda3/lib/python3.8/site-packages/docker/api/client.py", line 237, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/Users/tonysimonovskiy/opt/anaconda3/lib/python3.8/site-packages/requests/sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "/Users/tonysimonovskiy/opt/anaconda3/lib/python3.8/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/tonysimonovskiy/opt/anaconda3/lib/python3.8/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/Users/tonysimonovskiy/opt/anaconda3/lib/python3.8/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tonysimonovskiy/opt/anaconda3/bin/docker-compose", line 8, in <module>
    sys.exit(main())
  File "/Users/tonysimonovskiy/opt/anaconda3/lib/python3.8/site-packages/compose/cli/main.py", line 81, in main
    command_func()
  File "/Users/tonysimonovskiy/opt/anaconda3/lib/python3.8/site-packages/compose/cli/main.py", line 200, in perform_command
    project = project_from_options('.', options)
  File "/Users/tonysimonovskiy/opt/anaconda3/lib/python3.8/site-packages/compose/cli/command.py", line 60, in project_from_options
    return get_project(
  File "/Users/tonysimonovskiy/opt/anaconda3/lib/python3.8/site-packages/compose/cli/command.py", line 152, in get_project
    client = get_client(
  File "/Users/tonysimonovskiy/opt/anaconda3/lib/python3.8/site-packages/compose/cli/docker_client.py", line 41, in get_client
    client = docker_client(
  File "/Users/tonysimonovskiy/opt/anaconda3/lib/python3.8/site-packages/compose/cli/docker_client.py", line 170, in docker_client
    client = APIClient(use_ssh_client=not use_paramiko_ssh, **kwargs)
  File "/Users/tonysimonovskiy/opt/anaconda3/lib/python3.8/site-packages/docker/api/client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
  File "/Users/tonysimonovskiy/opt/anaconda3/lib/python3.8/site-packages/docker/api/client.py", line 221, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
```

**Comment by gaivalue** [comment]
> 

Nope

**Comment by karfly** [comment]
Do you have your `config.env` file?

**Comment by clemsau** [comment]
I think it is the same issue as #132 
Could you confirm that you have docker running with `systemctl status docker` ?
