### ISSUE TITLE
Dump AttributeError: 'NoneType' object has no attribute 'from_user'"

### ISSUE THREAD

**Issue by HAtestowy02** [karfly/chatgpt_telegram_bot#169]
When i clone project to own serv i have problem witch bot:
```
An exception was raised while handling an update
update = {
  "update_id": 223957514,
  "channel_post": {
    "chat": {
      "id": -1001190846475,
      "type": "channel",
      "title": "BOTBOTGPT"
    },
    "text": "test",
    "group_chat_created": false,
    "message_id": 33,
    "delete_chat_photo": false,
    "sender_chat": {
      "id": -1001190846475,
      "type": "channel",
      "title": "BOTBOTGPT"
    },
    "date": 1679532639,
    "supergroup_chat_created": false,
    "channel_chat_created": false
  }
}

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/telegram/ext/_[application.py](https://application.py/)", line 1104, in process_update
    await coroutine
  File "/usr/local/lib/python3.8/site-packages/telegram/ext/_[handler.py](https://handler.py/)", line 141, in handle_update
    return await self.callback(update, context)
  File "bot/[bot.py](https://bot.py/)", line 139, in message_handle
    await register_user_if_not_exists(update, context, update.message.from_user)
AttributeError: 'NoneType' object has no attribute 'from_user'
```
From http://localhost:8081/ db  chatgpt_telegram_bot is empty but bot on telegram receive dump data.
I have mongo:4.4.19 because of AVX problem and i try with mongo-express:0.54.0 and :latest.
Please help me with this issue.

**Comment by HAtestowy02** [comment]
It happened on quite fresh Ubuntu 22.04 LTS

**Comment by karfly** [comment]
I also get this error from time to time, but still don't know how to fix it
