### ISSUE TITLE
Trying to start new dialog on start throws an exception

### ISSUE THREAD

**Issue by Barmem** [karfly/chatgpt_telegram_bot#207]
NAME, [06.04.2023 0:09]
/start

chatgpt_telegram_bot, [06.04.2023 0:09]
Hi! I'm ChatGPT bot implemented with GPT-3.5 OpenAI API 🤖

Commands:
⚪ /retry – Regenerate last bot answer
⚪ /new – Start new dialog
⚪ /mode – Select chat mode
⚪ /settings – Show settings
⚪ /balance – Show balance
⚪ /help – Show help

And now... ask me anything!

NAME, [06.04.2023 0:09]
/new

chatgpt_telegram_bot, [06.04.2023 0:09]
Starting new dialog ✅

chatgpt_telegram_bot, [06.04.2023 0:09]
```
An exception was raised while handling an update
update = {
  "update_id": *********,
  "message": {
    "chat": {
      "id": *********,
      "type": "private",
      "first_name": "NAME",
      "username": "USERNAME"
    },
    "text": "/new",
    "group_chat_created": false,
    "entities": [
      {
        "length": 4,
        "type": "bot_command",
        "offset": 0
      }
    ],
    "message_id": 3,
    "delete_chat_photo": false,
    "date": 1680718200,
    "supergroup_chat_created": false,
    "channel_chat_created": false,
    "from": {
      "is_bot": false,
      "username": "USERNAME",
      "first_name": "NAME",
      "id": *********,
      "language_code": "LANG"
    }
  }
}

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/telegram/ext/_application.py", line 1104, in process_update
    await coroutine
  File "/usr/local/lib/python3.8/site-packages/telegram/ext/_handler.py", line 141, in handle_update
    return await self.callback(update, context)
  File "bot/bot.py", line 312, in new_dialog_handle
    await update.message.reply_text(f"{openai_utils.CHAT_MODES[chat_mode]['welcome_message']}", parse_mode=ParseMode.HTML)
KeyError: 'assistant'
```

**Comment by BilalZahidShah** [comment]
yeah I m getting the same error too

**Comment by karfly** [comment]
`assistant` must be in `chat_modes.yml` file
