### ISSUE TITLE
failed to build

### ISSUE THREAD

**Issue by krimtsev** [karfly/chatgpt_telegram_bot#234]
![ezgif-5-c65315b408](https://user-images.githubusercontent.com/12584409/231904894-579c1da4-f865-48da-ab52-735e0e4df463.gif)

`An exception was raised while handling an update
update = {
  "update_id": 767634406,
  "message": {
    "chat": {
      "id": 447456,
      "type": "private",
      "first_name": "kpm",
      "username": "krimtsev"
    },
    "text": "/start",
    "group_chat_created": false,
    "entities": [
      {
        "length": 6,
        "type": "bot_command",
        "offset": 0
      }
    ],
    "message_id": 1076,
    "delete_chat_photo": false,
    "date": 1681428679,
    "supergroup_chat_created": false,
    "channel_chat_created": false,
    "from": {
      "is_bot": false,
      "username": "krimtsev",
      "first_name": "kpm",
      "id": 447456,
      "language_code": "ru"
    }
  }
}

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/telegram/ext/_application.py", line 1104, in process_update
    await coroutine
  File "/usr/local/lib/python3.8/site-packages/telegram/ext/_handler.py", line 141, in handle_update
    return await self.callback(update, context)
  File "bot/bot.py", line 96, in start_handle
    await register_user_if_not_exists(update, context, update.message.from_user)
  File "bot/bot.py", line 60, in register_user_if_not_exists
    if not db.check_if_user_exists(user.id):
  File "/code/bot/database.py", line 19, in check_if_user_exists
    if self.user_collection.count_documents({"_id": user_id}) > 0:
  File "/usr/local/lib/python3.8/site-packages/pymongo/collection.py", line 1842, in count_documents
    return self._retryable_non_cursor_read(_cmd, session)
  File "/usr/local/lib/python3.8/site-packages/pymongo/collection.py", line 1847, in _retryable_non_cursor_read
    with client._tmp_session(session) as s:
  File "/usr/local/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1757, in _tmp_session
    s = self._ensure_session(session)
  File "/usr/local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1740, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/usr/local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1685, in __start_session
    self._topology._check_implicit_session_support()
  File "/usr/local/lib/python3.8/site-packages/pymongo/topology.py", line 538, in _check_implicit_session_support
    self._check_session_support()
  File "/usr/local/lib/python3.8/site-packages/pymongo/topology.py", line 554, in _check_session_support
    self._select_servers_loop(
  File "/usr/local/lib/python3.8/site-packages/pymongo/topology.py", line 238, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: mongo:27017: [Errno -2] Name or service not known, Timeout: 30s, Topology Description: <TopologyDescription id: 643890a1e0e28a3c58ad9975, topology_type: Unknown, servers: [<ServerDescription ('mongo', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('mongo:27017: [Errno -2] Name or service not known')>]>`

**Comment by krimtsev** [comment]
To begin with, I enabled AVX support for the virtual machine, and now the error has changed

**Comment by krimtsev** [comment]
![Screenshot_49](https://user-images.githubusercontent.com/12584409/231954112-02ae299c-c136-4dbc-826e-5cfbf1c77a9a.png)
