### ISSUE TITLE
Длинный диалог в аудио telegram.error.BadRequest: Message is too long

### ISSUE THREAD

**Issue by salesevolution** [karfly/chatgpt_telegram_bot#244]
При попытке загрузить запись телефонного разговора с активным общением длиной 8 минут 

`An exception was raised while handling an update
update = {
  "update_id": 247076013,
  "message": {
    "chat": {
      "id": ????????,
      "type": "private",
      "last_name": "????????",
      "first_name": "????????",
      "username": "????????"
    },
    "group_chat_created": false,
    "caption": "",
    "message_id": 8680,
    "delete_chat_photo": false,
    "voice": {
      "duration": 0,
      "mime_type": "audio/ogg",
      "file_id": "AwACAgIAAxkBAAIh6GRBP9evj6XIvn_FpH_XDbHLriLxAAJhLgACZv4ISsYMtkWK6Mi8LwQ",
      "file_size": 2320375,
      "file_unique_id": "AgADYS4AAmb-CEo"
    },
    "date": 1681997783,
    "supergroup_chat_created": false,
    "channel_chat_created": false,
    "from": {
      "is_bot": false,
      "username": "????????",
      "first_name": "????????",
      "last_name": "????????",
      "id": ????????,
      "language_code": "ru",
      "is_premium": true
    }
  }
}

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/telegram/ext/_application.py", line 1104, in process_update
    await coroutine
  File "/usr/local/lib/python3.8/site-packages/telegram/ext/_handler.py", line 141, in handle_update
    return await self.callback(update, context)
  File "bot/bot.py", line 293, in voice_message_handle
    await update.message.reply_text(text, parse_mode=ParseMode.HTML)
  File "/usr/local/lib/python3.8/site-packages/telegram/_message.py", line 1041, in reply_text
    return await self.get_bot().send_message(
  File "/usr/local/lib/python3.8/site-packages/telegram/ext/_extbot.py", line 2598, in send_message
    return await super().send_message(
  File "/usr/local/lib/python3.8/site-packages/telegram/_bot.py", line 331, in decorator
    result = await func(*args, **kwargs)  # skipcq: PYL-E1102
  File "/usr/local/lib/python3.8/site-packages/telegram/_bot.py", line 760, in send_message
    return await self._send_message(
  File "/usr/local/lib/python3.8/site-packages/telegram/ext/_extbot.py", line 488, in _send_message
    result = await super()._send_message(
  File "/usr/local/lib/python3.8/site-packages/telegram/_bot.py", line 512, in _send_message
    result = await self._post(
  File "/usr/local/lib/python3.8/site-packages/telegram/_bot.py", line 419, in _post
    return await self._do_post(
  File "/usr/local/lib/python3.8/site-packages/telegram/ext/_extbot.py", line 326, in _do_post
    return await self.rate_limiter.process_request(
  File "/usr/local/lib/python3.8/site-packages/telegram/ext/_aioratelimiter.py", line 247, in process_request
    return await self._run_request(
  File "/usr/local/lib/python3.8/site-packages/telegram/ext/_aioratelimiter.py", line 203, in _run_request
    return await callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/telegram/_bot.py", line 450, in _do_post
    return await request.post(
  File "/usr/local/lib/python3.8/site-packages/telegram/request/_baserequest.py", line 165, in post
    result = await self._request_wrapper(
  File "/usr/local/lib/python3.8/site-packages/telegram/request/_baserequest.py", line 328, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Message is too long`

**Comment by salesevolution** [comment]
Эта ошибка возникает, когда вы пытаетесь отправить сообщение, которое превышает максимально допустимый размер сообщения в Telegram. Максимальный размер сообщения в Telegram - 4096 символов.

В вашем случае, скорее всего, сообщение, которое вы пытаетесь отправить, содержит более 4096 символов. Чтобы решить эту проблему, вам нужно уменьшить размер сообщения или разбить его на несколько более коротких сообщений.

**Comment by salesevolution** [comment]
Если проблема связана с транскрипцией аудио, то возможно, лучшим решением будет разбить транскрипцию на несколько сообщений и отправить их по очереди. Вы можете использовать функцию Python для разбиения строк на подстроки с заданной длиной, например:

```python
def split_text(text, length=4096):
    return [text[i:i+length] for i in range(0, len(text), length)]
```

Эта функция будет разбивать текст на части длиной не более 4096 символов. Вы можете использовать ее для разбиения транскрипции на несколько сообщений и отправки их по очереди.
