### ISSUE TITLE
Error while getting Updates

### ISSUE THREAD

**Issue by Klansik** [karfly/chatgpt_telegram_bot#262]
I have the next error trace. I have not any other bots running on the machine. Down here I represent the errors trace (such errors appear again and again). Please help =)

```
Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
chatgpt_telegram_bot    | Exception while handling an update:
chatgpt_telegram_bot    | Traceback (most recent call last):
chatgpt_telegram_bot    |   File "/usr/local/lib/python3.8/site-packages/telegram/ext/_updater.py", line 607, in _network_loop_retry
chatgpt_telegram_bot    |     if not await action_cb():
chatgpt_telegram_bot    |   File "/usr/local/lib/python3.8/site-packages/telegram/ext/_updater.py", line 335, in polling_action_cb
chatgpt_telegram_bot    |     raise exc
chatgpt_telegram_bot    |   File "/usr/local/lib/python3.8/site-packages/telegram/ext/_updater.py", line 320, in polling_action_cb
chatgpt_telegram_bot    |     updates = await self.bot.get_updates(
chatgpt_telegram_bot    |   File "/usr/local/lib/python3.8/site-packages/telegram/ext/_extbot.py", line 524, in get_updates
chatgpt_telegram_bot    |     updates = await super().get_updates(
chatgpt_telegram_bot    |   File "/usr/local/lib/python3.8/site-packages/telegram/_bot.py", line 331, in decorator
chatgpt_telegram_bot    |     result = await func(*args, **kwargs)  # skipcq: PYL-E1102
chatgpt_telegram_bot    |   File "/usr/local/lib/python3.8/site-packages/telegram/_bot.py", line 3510, in get_updates
chatgpt_telegram_bot    |     await self._post(
chatgpt_telegram_bot    |   File "/usr/local/lib/python3.8/site-packages/telegram/_bot.py", line 419, in _post
chatgpt_telegram_bot    |     return await self._do_post(
chatgpt_telegram_bot    |   File "/usr/local/lib/python3.8/site-packages/telegram/ext/_extbot.py", line 306, in _do_post
chatgpt_telegram_bot    |     return await super()._do_post(
chatgpt_telegram_bot    |   File "/usr/local/lib/python3.8/site-packages/telegram/_bot.py", line 450, in _do_post
chatgpt_telegram_bot    |     return await request.post(
chatgpt_telegram_bot    |   File "/usr/local/lib/python3.8/site-packages/telegram/request/_baserequest.py", line 165, in post
chatgpt_telegram_bot    |     result = await self._request_wrapper(
chatgpt_telegram_bot    |   File "/usr/local/lib/python3.8/site-packages/telegram/request/_baserequest.py", line 330, in _request_wrapper
chatgpt_telegram_bot    |     raise Conflict(message)
chatgpt_telegram_bot    | telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
chatgpt_telegram_bot    | An error was raised and an uncaught error was raised while handling the error with an error_handler.
chatgpt_telegram_bot    | Traceback (most recent call last):
chatgpt_telegram_bot    |   File "bot/bot.py", line 645, in error_handle
chatgpt_telegram_bot    |     await context.bot.send_message(update.effective_chat.id, message_chunk, parse_mode=ParseMode.HTML)
chatgpt_telegram_bot    | AttributeError: 'NoneType' object has no attribute 'effective_chat'
chatgpt_telegram_bot    | 
chatgpt_telegram_bot    | During handling of the above exception, another exception occurred:
chatgpt_telegram_bot    | 
chatgpt_telegram_bot    | Traceback (most recent call last):
chatgpt_telegram_bot    |   File "/usr/local/lib/python3.8/site-packages/telegram/ext/_application.py", line 1617, in process_error
chatgpt_telegram_bot    |     await callback(update, context)
chatgpt_telegram_bot    |   File "bot/bot.py", line 650, in error_handle
chatgpt_telegram_bot    |     await context.bot.send_message(update.effective_chat.id, "Some error in error handler")
chatgpt_telegram_bot    | AttributeError: 'NoneType' object has no attribute 'effective_chat'
chatgpt_telegram_bot    | Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
chatgpt_telegram_bot    | Exception while handling an update:
chatgpt_telegram_bot    | Traceback (most recent call last):
chatgpt_telegram_bot    |   File "/usr/local/lib/python3.8/site-packages/telegram/ext/_updater.py", line 607, in _network_loop_retry
chatgpt_telegram_bot    |     if not await action_cb():
chatgpt_telegram_bot    |   File "/usr/local/lib/python3.8/site-packages/telegram/ext/_updater.py", line 335, in polling_action_cb
chatgpt_telegram_bot    |     raise exc
chatgpt_telegram_bot    |   File "/usr/local/lib/python3.8/site-packages/telegram/ext/_updater.py", line 320, in polling_action_cb
chatgpt_telegram_bot    |     updates = await self.bot.get_updates(
chatgpt_telegram_bot    |   File "/usr/local/lib/python3.8/site-packages/telegram/ext/_extbot.py", line 524, in get_updates
chatgpt_telegram_bot    |     updates = await super().get_updates(
chatgpt_telegram_bot    |   File "/usr/local/lib/python3.8/site-packages/telegram/_bot.py", line 331, in decorator
chatgpt_telegram_bot    |     result = await func(*args, **kwargs)  # skipcq: PYL-E1102
chatgpt_telegram_bot    |   File "/usr/local/lib/python3.8/site-packages/telegram/_bot.py", line 3510, in get_updates
chatgpt_telegram_bot    |     await self._post(
chatgpt_telegram_bot    |   File "/usr/local/lib/python3.8/site-packages/telegram/_bot.py", line 419, in _post
chatgpt_telegram_bot    |     return await self._do_post(
chatgpt_telegram_bot    |   File "/usr/local/lib/python3.8/site-packages/telegram/ext/_extbot.py", line 306, in _do_post
chatgpt_telegram_bot    |     return await super()._do_post(
chatgpt_telegram_bot    |   File "/usr/local/lib/python3.8/site-packages/telegram/_bot.py", line 450, in _do_post
chatgpt_telegram_bot    |     return await request.post(
chatgpt_telegram_bot    |   File "/usr/local/lib/python3.8/site-packages/telegram/request/_baserequest.py", line 165, in post
chatgpt_telegram_bot    |     result = await self._request_wrapper(
chatgpt_telegram_bot    |   File "/usr/local/lib/python3.8/site-packages/telegram/request/_baserequest.py", line 330, in _request_wrapper
chatgpt_telegram_bot    |     raise Conflict(message)
chatgpt_telegram_bot    | telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
chatgpt_telegram_bot    | An error was raised and an uncaught error was raised while handling the error with an error_handler.
chatgpt_telegram_bot    | Traceback (most recent call last):
chatgpt_telegram_bot    |   File "bot/bot.py", line 645, in error_handle
chatgpt_telegram_bot    |     await context.bot.send_message(update.effective_chat.id, message_chunk, parse_mode=ParseMode.HTML)
chatgpt_telegram_bot    | AttributeError: 'NoneType' object has no attribute 'effective_chat'
```

**Comment by Klansik** [comment]
I cleared mongo-database, change telegram apikey and removed and started again all docker containers and then I haven't these errors but bot is not answering me now and I have another error trace (below):

```
Exception while handling an update:
chatgpt_telegram_bot    | Traceback (most recent call last):
chatgpt_telegram_bot    |   File "/usr/local/lib/python3.8/site-packages/telegram/ext/_application.py", line 1104, in process_update
chatgpt_telegram_bot    |     await coroutine
chatgpt_telegram_bot    |   File "/usr/local/lib/python3.8/site-packages/telegram/ext/_handler.py", line 141, in handle_update
chatgpt_telegram_bot    |     return await self.callback(update, context)
chatgpt_telegram_bot    |   File "bot/bot.py", line 200, in message_handle
chatgpt_telegram_bot    |     await register_user_if_not_exists(update, context, update.message.from_user)
chatgpt_telegram_bot    |   File "bot/bot.py", line 76, in register_user_if_not_exists
chatgpt_telegram_bot    |     if not db.check_if_user_exists(user.id):
chatgpt_telegram_bot    |   File "/code/bot/database.py", line 19, in check_if_user_exists
chatgpt_telegram_bot    |     if self.user_collection.count_documents({"_id": user_id}) > 0:
chatgpt_telegram_bot    |   File "/usr/local/lib/python3.8/site-packages/pymongo/collection.py", line 1842, in count_documents
chatgpt_telegram_bot    |     return self._retryable_non_cursor_read(_cmd, session)
chatgpt_telegram_bot    |   File "/usr/local/lib/python3.8/site-packages/pymongo/collection.py", line 1847, in _retryable_non_cursor_read
chatgpt_telegram_bot    |     with client._tmp_session(session) as s:
chatgpt_telegram_bot    |   File "/usr/local/lib/python3.8/contextlib.py", line 113, in __enter__
chatgpt_telegram_bot    |     return next(self.gen)
chatgpt_telegram_bot    |   File "/usr/local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1757, in _tmp_session
chatgpt_telegram_bot    |     s = self._ensure_session(session)
chatgpt_telegram_bot    |   File "/usr/local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1740, in _ensure_session
chatgpt_telegram_bot    |     return self.__start_session(True, causal_consistency=False)
chatgpt_telegram_bot    |   File "/usr/local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1685, in __start_session
chatgpt_telegram_bot    |     self._topology._check_implicit_session_support()
chatgpt_telegram_bot    |   File "/usr/local/lib/python3.8/site-packages/pymongo/topology.py", line 538, in _check_implicit_session_support
chatgpt_telegram_bot    |     self._check_session_support()
chatgpt_telegram_bot    |   File "/usr/local/lib/python3.8/site-packages/pymongo/topology.py", line 554, in _check_session_support
chatgpt_telegram_bot    |     self._select_servers_loop(
chatgpt_telegram_bot    |   File "/usr/local/lib/python3.8/site-packages/pymongo/topology.py", line 238, in _select_servers_loop
chatgpt_telegram_bot    |     raise ServerSelectionTimeoutError(
chatgpt_telegram_bot    | pymongo.errors.ServerSelectionTimeoutError: mongo:27017: [Errno -3] Temporary failure in name resolution, Timeout: 30s, Topology Description: <TopologyDescription id: 644a59868ff60bddde88e3e3, topology_type: Unknown, servers: [<ServerDescription ('mongo', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('mongo:27017: [Errno -3] Temporary failure in name resolution')>]>
```
