### ISSUE TITLE
The installation failed, it seems that the file directory cannot be found

### ISSUE THREAD

**Issue by hopegift** [karfly/chatgpt_telegram_bot#267]
_Ubuntu 20.04 64 Bit，A month ago, v1.3 was successfully installed, but when I wanted to reinstall the system, the following error occurred when I installed v1.4
v 1.3 is OK_

**slove the problem.Cannot directly use "git clone" to load the latest code, wget v1.4, and then edit config without reporting an error**

```
chatgpt_telegram_bot    | Traceback (most recent call last):
chatgpt_telegram_bot    |   File "bot/bot.py", line 33, in <module>
chatgpt_telegram_bot    |     import config
chatgpt_telegram_bot    |   File "/code/bot/config.py", line 27, in <module>
chatgpt_telegram_bot    |     chat_modes = yaml.safe_load(f)
chatgpt_telegram_bot    |   File "/usr/local/lib/python3.8/site-packages/yaml/__init__.py", line 125, in safe_load
chatgpt_telegram_bot    |     return load(stream, SafeLoader)
chatgpt_telegram_bot    |   File "/usr/local/lib/python3.8/site-packages/yaml/__init__.py", line 81, in load
chatgpt_telegram_bot    |     return loader.get_single_data()
chatgpt_telegram_bot    |   File "/usr/local/lib/python3.8/site-packages/yaml/constructor.py", line 49, in get_single_data
chatgpt_telegram_bot    |     node = self.get_single_node()
chatgpt_telegram_bot    |   File "/usr/local/lib/python3.8/site-packages/yaml/composer.py", line 36, in get_single_node
chatgpt_telegram_bot    |     document = self.compose_document()
chatgpt_telegram_bot    |   File "/usr/local/lib/python3.8/site-packages/yaml/composer.py", line 55, in compose_document
chatgpt_telegram_bot    |     node = self.compose_node(None, None)
chatgpt_telegram_bot    |   File "/usr/local/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
chatgpt_telegram_bot    |     node = self.compose_mapping_node(anchor)
chatgpt_telegram_bot    |   File "/usr/local/lib/python3.8/site-packages/yaml/composer.py", line 133, in compose_mapping_node
chatgpt_telegram_bot    |     item_value = self.compose_node(node, item_key)
chatgpt_telegram_bot    |   File "/usr/local/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
chatgpt_telegram_bot    |     node = self.compose_mapping_node(anchor)
chatgpt_telegram_bot    |   File "/usr/local/lib/python3.8/site-packages/yaml/composer.py", line 127, in compose_mapping_node
chatgpt_telegram_bot    |     while not self.check_event(MappingEndEvent):
chatgpt_telegram_bot    |   File "/usr/local/lib/python3.8/site-packages/yaml/parser.py", line 98, in check_event
chatgpt_telegram_bot    |     self.current_event = self.state()
chatgpt_telegram_bot    |   File "/usr/local/lib/python3.8/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
chatgpt_telegram_bot    |     if self.check_token(KeyToken):
chatgpt_telegram_bot    |   File "/usr/local/lib/python3.8/site-packages/yaml/scanner.py", line 116, in check_token
chatgpt_telegram_bot    |     self.fetch_more_tokens()
chatgpt_telegram_bot    |   File "/usr/local/lib/python3.8/site-packages/yaml/scanner.py", line 223, in fetch_more_tokens
chatgpt_telegram_bot    |     return self.fetch_value()
chatgpt_telegram_bot    |   File "/usr/local/lib/python3.8/site-packages/yaml/scanner.py", line 577, in fetch_value
chatgpt_telegram_bot    |     raise ScannerError(None, None,
chatgpt_telegram_bot    | yaml.scanner.ScannerError: mapping values are not allowed here
chatgpt_telegram_bot    |   in "/code/config/chat_modes.yml", line 3, column 18
chatgpt_telegram_bot exited with code 1
```

**Comment by crypticatul** [comment]
Same here
