### ISSUE TITLE
how to fix this, mongodb exited with code 132

### ISSUE THREAD

**Issue by bpkddr** [karfly/chatgpt_telegram_bot#289]
`Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/telegram/ext/_application.py", line 1104, in process_update
    await coroutine
  File "/usr/local/lib/python3.8/site-packages/telegram/ext/_handler.py", line 141, in handle_update
    return await self.callback(update, context)
  File "bot/bot.py", line 403, in new_dialog_handle
    await register_user_if_not_exists(update, context, update.message.from_user)
  File "bot/bot.py", line 76, in register_user_if_not_exists
    if not db.check_if_user_exists(user.id):
  File "/code/bot/database.py", line 19, in check_if_user_exists
    if self.user_collection.count_documents({"_id": user_id}) > 0:
  File "/usr/local/lib/python3.8/site-packages/pymongo/collection.py", line 1842, in count_documents
    return self._retryable_non_cursor_read(_cmd, session)
  File "/usr/local/lib/python3.8/site-packages/pymongo/collection.py", line 1847, in _retryable_non_cursor_read
    with client._tmp_session(session) as s:
  File "/usr/local/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1757, in _tmp_session
    s = self._ensure_session(session)
  File "/usr/local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1740, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/usr/local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1685, in __start_session
    self._topology._check_implicit_session_support()
  File "/usr/local/lib/python3.8/site-packages/pymongo/topology.py", line 538, in _check_implicit_session_support
    self._check_session_support()
  File "/usr/local/lib/python3.8/site-packages/pymongo/topology.py", line 554, in _check_session_support
    self._select_servers_loop(
  File "/usr/local/lib/python3.8/site-packages/pymongo/topology.py", line 238, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: mongo:27017: [Errno -3] Temporary failure in name resolution, Timeout: 30s, Topology Description: <TopologyDescription id: 646ba152464dc5ee9e0a795d, topology_type: Unknown, servers: [<ServerDescription ('mongo', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('mongo:27017: [Errno -3] Temporary failure in name resolution')>]>`

**Comment by karfly** [comment]
Looks like your mongo service haven't been started. Did you use docker-compose command from README?

**Comment by mxwmnn** [comment]
Same error. 

Used to command from README but without '-' cause i dont have docker-compose. i can only use 'docker compose'.
Nearly everything worked, except the thing with mongodb.
I got a lot of deprecation warnings through the build. And then the exit 132.

I already got the bot running months ago, but not now anymore.

**Comment by karfly** [comment]
Can't reproduce the error. Does anybody know how to fix it?

**Comment by mxwmnn** [comment]
Im on debian 11. Last time i used fedora and it worked.. 

In portainer, every service shows running, but with the logs mentioned above...

With which system did u try it?

**Comment by karfly** [comment]
Can you send your `allowed_telegram_usernames` field from config, which **doesn't** work?

**Comment by SeriousJokes** [comment]
Hi everyone! I also get this 132 error, when I try to run `sudo docker-compose --env-file config/config.env up --build` command. I didn't add anything in `allowed_telegram_usernames` field, so I don't think this causes the problem.
I am trying to run it in **_Ubuntu 22.04.3 LTS_** on my Raspberry Pi 3B+.

**Comment by SeriousJokes** [comment]
Here's the error output. As you can see, mongo and mongo-express started.

```
Successfully built 55c1270f87e9
Successfully tagged chatgpt_telegram_bot_chatgpt_telegram_bot:latest
Starting mongo ... done
Starting chatgpt_telegram_bot ... done
Starting mongo-express        ... done
Attaching to mongo, chatgpt_telegram_bot, mongo-express
mongo                   | 
mongo                   | WARNING: MongoDB requires ARMv8.2-A or higher, and your current system does not appear to implement any of the common features for that!
mongo                   |   applies to all versions ≥5.0, any of 4.4 ≥4.4.19
mongo                   |   see https://jira.mongodb.org/browse/SERVER-71772
mongo                   |   see https://jira.mongodb.org/browse/SERVER-55178
mongo                   |   see also https://en.wikichip.org/wiki/arm/armv8#ARMv8_Extensions_and_Processor_Features
mongo                   |   see also https://github.com/docker-library/mongo/issues/485#issuecomment-970864306
mongo                   | 
mongo                   | 
mongo                   | WARNING: MongoDB requires ARMv8.2-A or higher, and your current system does not appear to implement any of the common features for that!
mongo                   |   applies to all versions ≥5.0, any of 4.4 ≥4.4.19
mongo                   |   see https://jira.mongodb.org/browse/SERVER-71772
mongo                   |   see https://jira.mongodb.org/browse/SERVER-55178
mongo                   |   see also https://en.wikichip.org/wiki/arm/armv8#ARMv8_Extensions_and_Processor_Features
mongo                   |   see also https://github.com/docker-library/mongo/issues/485#issuecomment-970864306
mongo                   | 
mongo exited with code 132
mongo                   | 
mongo                   | WARNING: MongoDB requires ARMv8.2-A or higher, and your current system does not appear to implement any of the common features for that!
mongo                   |   applies to all versions ≥5.0, any of 4.4 ≥4.4.19
mongo                   |   see https://jira.mongodb.org/browse/SERVER-71772
mongo                   |   see https://jira.mongodb.org/browse/SERVER-55178
mongo                   |   see also https://en.wikichip.org/wiki/arm/armv8#ARMv8_Extensions_and_Processor_Features
mongo                   |   see also https://github.com/docker-library/mongo/issues/485#issuecomment-970864306
mongo                   | 
mongo-express           | Welcome to mongo-express
mongo-express           | ------------------------
mongo-express           | 
mongo-express           | 
mongo-express           | (node:7) [MONGODB DRIVER] Warning: Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
mongo-express           | Could not connect to database using connectionString: mongodb://mongo:27017/chatgpt_telegram_bot"
mongo-express           | (node:7) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [mongo:27017] on first connect [Error: connect ECONNREFUSED 172.18.0.2:27017
mongo-express           |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) {
mongo-express           |   name: 'MongoNetworkError'
mongo-express           | }]
mongo-express           |     at Pool.<anonymous> (/node_modules/mongodb/lib/core/topologies/server.js:441:11)
mongo-express           |     at Pool.emit (events.js:314:20)
mongo-express           |     at /node_modules/mongodb/lib/core/connection/pool.js:564:14
mongo-express           |     at /node_modules/mongodb/lib/core/connection/pool.js:1000:11
mongo-express           |     at /node_modules/mongodb/lib/core/connection/connect.js:32:7
mongo-express           |     at callback (/node_modules/mongodb/lib/core/connection/connect.js:300:5)
mongo-express           |     at Socket.<anonymous> (/node_modules/mongodb/lib/core/connection/connect.js:330:7)
mongo-express           |     at Object.onceWrapper (events.js:421:26)
mongo-express           |     at Socket.emit (events.js:314:20)
mongo-express           |     at emitErrorNT (internal/streams/destroy.js:92:8)
mongo-express           |     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
mongo-express           |     at processTicksAndRejections (internal/process/task_queues.js:84:21)
mongo-express           | (node:7) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
mongo-express           | (node:7) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
mongo exited with code 132
mongo                   | 
mongo                   | WARNING: MongoDB requires ARMv8.2-A or higher, and your current system does not appear to implement any of the common features for that!
mongo                   |   applies to all versions ≥5.0, any of 4.4 ≥4.4.19
mongo                   |   see https://jira.mongodb.org/browse/SERVER-71772
mongo                   |   see https://jira.mongodb.org/browse/SERVER-55178
mongo                   |   see also https://en.wikichip.org/wiki/arm/armv8#ARMv8_Extensions_and_Processor_Features
mongo                   |   see also https://github.com/docker-library/mongo/issues/485#issuecomment-970864306
mongo                   | 
mongo exited with code 132
mongo-express           | Welcome to mongo-express
mongo-express           | ------------------------
mongo-express           | 
mongo-express           | 
mongo-express           | (node:8) [MONGODB DRIVER] Warning: Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
mongo-express           | Could not connect to database using connectionString: mongodb://mongo:27017/chatgpt_telegram_bot"
mongo-express           | (node:8) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [mongo:27017] on first connect [Error: connect ECONNREFUSED 172.18.0.2:27017
mongo-express           |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) {
mongo-express           |   name: 'MongoNetworkError'
mongo-express           | }]
mongo-express           |     at Pool.<anonymous> (/node_modules/mongodb/lib/core/topologies/server.js:441:11)
mongo-express           |     at Pool.emit (events.js:314:20)
mongo-express           |     at /node_modules/mongodb/lib/core/connection/pool.js:564:14
mongo-express           |     at /node_modules/mongodb/lib/core/connection/pool.js:1000:11
mongo-express           |     at /node_modules/mongodb/lib/core/connection/connect.js:32:7
mongo-express           |     at callback (/node_modules/mongodb/lib/core/connection/connect.js:300:5)
mongo-express           |     at Socket.<anonymous> (/node_modules/mongodb/lib/core/connection/connect.js:330:7)
mongo-express           |     at Object.onceWrapper (events.js:421:26)
mongo-express           |     at Socket.emit (events.js:314:20)
mongo-express           |     at emitErrorNT (internal/streams/destroy.js:92:8)
mongo-express           |     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
mongo-express           |     at processTicksAndRejections (internal/process/task_queues.js:84:21)
mongo-express           | (node:8) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
mongo-express           | (node:8) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
mongo                   | 
mongo                   | WARNING: MongoDB requires ARMv8.2-A or higher, and your current system does not appear to implement any of the common features for that!
mongo                   |   applies to all versions ≥5.0, any of 4.4 ≥4.4.19
mongo                   |   see https://jira.mongodb.org/browse/SERVER-71772
mongo                   |   see https://jira.mongodb.org/browse/SERVER-55178
mongo                   |   see also https://en.wikichip.org/wiki/arm/armv8#ARMv8_Extensions_and_Processor_Features
mongo                   |   see also https://github.com/docker-library/mongo/issues/485#issuecomment-970864306
mongo                   | 
mongo-express exited with code 0
mongo exited with code 132
^CGracefully stopping... (press Ctrl+C again to force)
Stopping chatgpt_telegram_bot ... done
Stopping mongo-express        ... done
Stopping mongo                ... done
```

**Comment by karfly** [comment]
@SeriousJokes looks like there is a problem with mongodb
Try this fix and write here if it works: https://github.com/karfly/chatgpt_telegram_bot/issues/133#issuecomment-1472601356

**Comment by SeriousJokes** [comment]
> @SeriousJokes looks like there is a problem with mongodb
> 
> Try this fix and write here if it works: https://github.com/karfly/chatgpt_telegram_bot/issues/133#issuecomment-1472601356

Man, have you been ranked Captain Obvious? 
I told, that this is a problem with mongodb. 
The question was "What is the problem?"

But now I think I see the problem. I need to downgrade mongodb version to 4.4, because newer versions can't be executed on my Raspberry hardware.
