### ISSUE TITLE
UnboundLocalError: local variable 'answer' referenced before assignment

### ISSUE THREAD

**Issue by vuisme** [karfly/chatgpt_telegram_bot#3]
I got that bug
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/telegram/ext/_application.py", line 945, in process_update
    await coroutine
  File "/usr/local/lib/python3.8/site-packages/telegram/ext/_handler.py", line 135, in handle_update
    return await self.callback(update, context)
  File "bot.py", line 84, in message_handle
    await update.message.reply_text(answer, parse_mode=ParseMode.HTML)
UnboundLocalError: local variable 'answer' referenced before assignment
```

**Comment by karfly** [comment]
Can you give more context on your problem?

**Comment by karfly** [comment]
Try to run the code with the latest commit 92d0c7ed758dffdcba62f1463b6103ac82cc8609
