### ISSUE TITLE
Bot answer bug

### ISSUE THREAD

**Issue by hoangnamitc** [karfly/chatgpt_telegram_bot#30]
Hi,

below is answer of bot some times.

`
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/telegram/ext/_application.py", line 945, in process_update
    await coroutine
  File "/usr/local/lib/python3.8/site-packages/telegram/ext/_handler.py", line 135, in handle_update
    return await self.callback(update, context)
  File "bot/bot.py", line 87, in message_handle
    await register_user_if_not_exists(update, context, update.message.from_user)
AttributeError: 'NoneType' object has no attribute 'from_user'
`

**Comment by karfly** [comment]
Can you share your whole dialog history?

**Comment by hoangnamitc** [comment]
I did the following:

- first my chat:
`hôm nay là thứ mâý`

- Bot reply:
`Hôm nay là thứ Bảy, ngày 10 tháng 5 năm 2020.`

**After me edit my message to**

`ngày tháng đầy đủ hôm nay`

- bot reply bug:
`An exception was raised while handling an update
update =`

**Comment by karfly** [comment]
I see. The problem with message editing. Now user gets "editing is not supported" message f2bc61714647c889a34401fce2b72e7bd070f28c
