### ISSUE TITLE
Error while fetching server API version: HTTPConnection.request() got an unexpected keyword argument 'chunked'

### ISSUE THREAD

**Issue by vasmarfas** [karfly/chatgpt_telegram_bot#324]
I followed your instructions, but while i run docker command, i get this error, how can i fix it?
```shell
root@instance-20230613-2339:/home/ubuntu/chatgpt_telegram_bot# docker-compose --env-file config/config.env up --build
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 214, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
  File "/usr/lib/python3/dist-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
  File "/usr/lib/python3/dist-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 237, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 496, in _make_request
    conn.request(
TypeError: HTTPConnection.request() got an unexpected keyword argument 'chunked'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 33, in <module>
    sys.exit(load_entry_point('docker-compose==1.29.2', 'console_scripts', 'docker-compose')())
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 81, in main
    command_func()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 200, in perform_command
    project = project_from_options('.', options)
  File "/usr/lib/python3/dist-packages/compose/cli/command.py", line 60, in project_from_options
    return get_project(
  File "/usr/lib/python3/dist-packages/compose/cli/command.py", line 152, in get_project
    client = get_client(
  File "/usr/lib/python3/dist-packages/compose/cli/docker_client.py", line 41, in get_client
    client = docker_client(
  File "/usr/lib/python3/dist-packages/compose/cli/docker_client.py", line 170, in docker_client
    client = APIClient(use_ssh_client=not use_paramiko_ssh, **kwargs)
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 221, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: HTTPConnection.request() got an unexpected keyword argument 'chunked'

```

**Comment by karfly** [comment]
Hi! Here are possible solutions from GPT-4. Can try them out?

The error you're experiencing is related to a compatibility issue between the versions of Docker SDK for Python and the Python `requests` library you are using.

The Docker SDK for Python uses the `requests` library to make HTTP requests. In your case, it's trying to make a chunked request, which means sending the request body in pieces (or "chunks") rather than all at once, to the Docker server. This is a feature that is only supported in certain versions of the `requests` library.

The error message `TypeError: HTTPConnection.request() got an unexpected keyword argument 'chunked'` is thrown because the version of `requests` you're using doesn't support chunked requests.

You can fix this issue by upgrading your `requests` library to a version that supports chunked requests. To do this, run the following command in your terminal:

```bash
pip install --upgrade requests
```

If you're already using the latest version of `requests` and still encountering the issue, it might be the case that you have multiple versions of `requests` installed and Python is using an older version. To check this, you can use the following command:

```bash
pip show requests
```

This will display the version of `requests` that is currently in use. If this isn't the latest version, you may need to uninstall the older versions.

If the problem still persists, you may need to update your Docker SDK for Python to match the updated `requests` library. You can do that using:

```bash
pip install --upgrade docker
```

**Comment by vasmarfas** [comment]
Thanks! pip install --upgrade docker solved this problem!

**Comment by karfly** [comment]
All thanks to GPT-4 😂
