### ISSUE TITLE
Deployment issues

### ISSUE THREAD

**Issue by Hochinwei** [karfly/chatgpt_telegram_bot#373]
Traceback (most recent call last):
chatgpt_telegram_bot  |   File "bot/bot.py", line 33, in <module>
chatgpt_telegram_bot  |     import config
chatgpt_telegram_bot  |   File "/code/bot/config.py", line 8, in <module>
chatgpt_telegram_bot  |     with open(config_dir / "config.yml", 'r') as f:
chatgpt_telegram_bot  | FileNotFoundError: [Errno 2] No such file or directory: '/code/config/config.yml'

I found a similar thread that was closed, but could not find the solution. I have already ensured my config files are renamed exactly as stated. What could be the issue?

**Comment by karfly** [comment]
Hmm. Could you run from chatgpt_telegram_bot: `ls config`?
