### ISSUE TITLE
An exception was raised while handling an update

### ISSUE THREAD

**Issue by 4D4937** [karfly/chatgpt_telegram_bot#82]
`An exception was raised while handling an update
update = {
  "update_id": 316017589,
  "message": {
    "chat": {
      "id": 1034481140,
      "type": "private",
      "first_name": "lib3r",
      "username": "lib3r"
    },
    "text": "你好",
    "group_chat_created": false,
    "message_id": 15,
    "delete_chat_photo": false,
    "date": 1678001104,
    "supergroup_chat_created": false,
    "channel_chat_created": false,
    "from": {
      "is_bot": false,
      "username": "lib3r",
      "first_name": "lib3r",
      "id": 1034481140,
      "language_code": "zh-hans"
    }
  }
}

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/telegram/ext/_application.py", line 1104, in process_update
    await coroutine
  File "/usr/local/lib/python3.8/site-packages/telegram/ext/_handler.py", line 141, in handle_update
    return await self.callback(update, context)
  File "bot/bot.py", line 96, in message_handle
    await register_user_if_not_exists(update, context, update.message.from_user)
  File "bot/bot.py", line 38, in register_user_if_not_exists
    if not db.check_if_user_exists(user.id):
  File "/code/bot/database.py", line 19, in check_if_user_exists
    if self.user_collection.count_documents({"_id": user_id}) > 0:
  File "/usr/local/lib/python3.8/site-packages/pymongo/collection.py", line 1842, in count_documents
    return self._retryable_non_cursor_read(_cmd, session)
  File "/usr/local/lib/python3.8/site-packages/pymongo/collection.py", line 1847, in _retryable_non_cursor_read
    with client._tmp_session(session) as s:
  File "/usr/local/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1757, in _tmp_session
    s = self._ensure_session(session)
  File "/usr/local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1740, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/usr/local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1685, in __start_session
    self._topology._check_implicit_session_support()
  File "/usr/local/lib/python3.8/site-packages/pymongo/topology.py", line 538, in _check_implicit_session_support
    self._check_session_support()
  File "/usr/local/lib/python3.8/site-packages/pymongo/topology.py", line 554, in _check_session_support
    self._select_servers_loop(
  File "/usr/local/lib/python3.8/site-packages/pymongo/topology.py", line 238, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerS`

![image](https://user-images.githubusercontent.com/24792768/222947969-2f58e573-17f7-44c2-8c5a-6daccce76157.png)

**Comment by karfly** [comment]
Check if your mongo db works

**Comment by 4D4937** [comment]
![image](https://user-images.githubusercontent.com/24792768/222949765-e17a232b-29fe-412e-b324-a8ddbc9f0c94.png)

**Comment by IzzakQ** [comment]
> ![image](https://user-images.githubusercontent.com/24792768/222949765-e17a232b-29fe-412e-b324-a8ddbc9f0c94.png)

how did u solve this problem?
