### ISSUE TITLE
Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

### ISSUE THREAD

**Issue by xawwnee** [karfly/chatgpt_telegram_bot#98]
**1. Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2. AttributeError: 'NoneType' object has no attribute 'effective_chat'**

```
Mar 8 12:21:32 PM  Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
Mar 8 12:21:32 PM  Exception while handling an update:
Mar 8 12:21:32 PM  Traceback (most recent call last):
Mar 8 12:21:32 PM    File "/opt/render/project/src/.venv/lib/python3.7/site-packages/telegram/ext/_updater.py", line 607, in _network_loop_retry
Mar 8 12:21:32 PM      if not await action_cb():
Mar 8 12:21:32 PM    File "/opt/render/project/src/.venv/lib/python3.7/site-packages/telegram/ext/_updater.py", line 335, in polling_action_cb
Mar 8 12:21:32 PM      raise exc
Mar 8 12:21:32 PM    File "/opt/render/project/src/.venv/lib/python3.7/site-packages/telegram/ext/_updater.py", line 327, in polling_action_cb
Mar 8 12:21:32 PM      allowed_updates=allowed_updates,
Mar 8 12:21:32 PM    File "/opt/render/project/src/.venv/lib/python3.7/site-packages/telegram/ext/_extbot.py", line 533, in get_updates
Mar 8 12:21:32 PM      api_kwargs=api_kwargs,
Mar 8 12:21:32 PM    File "/opt/render/project/src/.venv/lib/python3.7/site-packages/telegram/_bot.py", line 331, in decorator
Mar 8 12:21:32 PM      result = await func(*args, **kwargs)  # skipcq: PYL-E1102
Mar 8 12:21:32 PM    File "/opt/render/project/src/.venv/lib/python3.7/site-packages/telegram/_bot.py", line 3517, in get_updates
Mar 8 12:21:32 PM      api_kwargs=api_kwargs,
Mar 8 12:21:32 PM    File "/opt/render/project/src/.venv/lib/python3.7/site-packages/telegram/_bot.py", line 425, in _post
Mar 8 12:21:32 PM      pool_timeout=pool_timeout,
Mar 8 12:21:32 PM    File "/opt/render/project/src/.venv/lib/python3.7/site-packages/telegram/ext/_extbot.py", line 312, in _do_post
Mar 8 12:21:32 PM      read_timeout=read_timeout,
Mar 8 12:21:32 PM    File "/opt/render/project/src/.venv/lib/python3.7/site-packages/telegram/_bot.py", line 456, in _do_post
Mar 8 12:21:32 PM      pool_timeout=pool_timeout,
Mar 8 12:21:32 PM    File "/opt/render/project/src/.venv/lib/python3.7/site-packages/telegram/request/_baserequest.py", line 172, in post
Mar 8 12:21:32 PM      pool_timeout=pool_timeout,
Mar 8 12:21:32 PM    File "/opt/render/project/src/.venv/lib/python3.7/site-packages/telegram/request/_baserequest.py", line 330, in _request_wrapper
Mar 8 12:21:32 PM      raise Conflict(message)
Mar 8 12:21:32 PM  telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
Mar 8 12:21:32 PM  An error was raised and an uncaught error was raised while handling the error with an error_handler.
Mar 8 12:21:32 PM  Traceback (most recent call last):
Mar 8 12:21:32 PM    File "bot/bot.py", line 236, in error_handle
Mar 8 12:21:32 PM      await context.bot.send_message(update.effective_chat.id, message_chunk, parse_mode=ParseMode.HTML)
Mar 8 12:21:32 PM  AttributeError: 'NoneType' object has no attribute 'effective_chat'
Mar 8 12:21:32 PM  
Mar 8 12:21:32 PM  During handling of the above exception, another exception occurred:
Mar 8 12:21:32 PM  
Mar 8 12:21:32 PM  Traceback (most recent call last):
Mar 8 12:21:32 PM    File "/opt/render/project/src/.venv/lib/python3.7/site-packages/telegram/ext/_application.py", line 1617, in process_error
Mar 8 12:21:32 PM      await callback(update, context)
Mar 8 12:21:32 PM    File "bot/bot.py", line 238, in error_handle
Mar 8 12:21:32 PM      await context.bot.send_message(update.effective_chat.id, "Some error in error handler")
Mar 8 12:21:32 PM  AttributeError: 'NoneType' object has no attribute 'effective_chat'
```

**Comment by Klansik** [comment]
@xawwnee how did you resolve this error? I have the same errors while building, can u help me please?

**Comment by xawwnee** [comment]
> 

Though I am not using it anymore.

You can try modifying as following in (ln 233):

```
        # split text into multiple messages due to 4096 character limit
        message_chunk_size = 4000
        message_chunks = [message[i:i + message_chunk_size] for i in range(0, len(message), message_chunk_size)]
        for message_chunk in message_chunks:
            await context.bot.send_message(update.effective_chat.id, message_chunk, parse_mode=ParseMode.HTML)
    except:
        await context.bot.send_message(update.effective_chat.id, "Some error in error handler")
```

**Comment by RicoToothless** [comment]
> @xawwnee how did you resolve this error? I have the same errors while building, can u help me please?

This error means you use the same Telegram API key in different running services.

So you have to stop service and use different Telegram API key.

If you can't find the service, you can revoke the API key on `botfather`

Ref: https://stackoverflow.com/questions/69870914/conflict-terminated-by-other-getupdates-request-make-sure-that-only-one-bot-in
